name: Update Fishing VietNam

on:
  push:
    branches:
      - vfo

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Update Fishing VietNam
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VFO_HOST }}
        username: ${{ secrets.VFO_USERNAME }}
        key: ${{ secrets.VFO_SSH_KEY }}
        script_stop: true
        script: |
          # Force update to latest remote code (no conflicts)
          cd ~/addons-system/openeducat
          git fetch origin && git reset --hard origin/vfo
          
          # Sync openeducat directory with rsync (including deletions)
          rsync -av --delete ~/addons-system/openeducat/ /opt/custom-addons/
          
          # Restart Odoo service to apply changes
          sudo systemctl restart odoo